#Configuation for robot odometry EKF
# https://github.com/cra-ros-pkg/robot_localization/blob/noetic-devel/params/ekf_template.yaml
frequency: 50
two_d_mode: true
predict_to_current_time: true
transform_time_offset: 1.0
odom0: /dingo_velocity_controller/odom #x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
#odom0_queue_size: 2
odom0_differential: false
imu0: /imu/data
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              false, false, false]
#imu0_queue_size: 5
imu0_differential: false
map_frame: map              # Defaults to "map" if unspecified
odom_frame: odom
base_link_frame: base_link
world_frame: odom
